function toggleNav(){document.querySelector('.nav-links').classList.toggle('open')}
const DB={get(k,d){try{const v=localStorage.getItem('yadcode_'+k);return v?JSON.parse(v):d}catch{return d}},set(k,v){localStorage.setItem('yadcode_'+k,JSON.stringify(v))}};
function trackView(type,id){const views=DB.get('views',{});views[type]=views[type]||{};views[type][id]=(views[type][id]||0)+1;DB.set('views',views);DB.set('total_views',DB.get('total_views',0)+1)}
function getRecommended(){const lessons=DB.get('lessons',[]);return lessons.slice(0,6).sort(()=>Math.random()-0.5)}
function renderRecommend(){const box=document.getElementById('recommendBox');if(!box)return;const items=getRecommended();if(items.length===0){box.innerHTML='<p style="color:var(--text-muted)">Belum ada konten.</p>';return}box.innerHTML=items.map(l=>'<a href="learn.html" class="feature-card" onclick="trackView(\'lesson\',\''+l.id+'\')"><div class="feature-icon-svg" style="font-size:48px">'+l.icon+'</div><h3>'+l.title+'</h3><p>'+l.desc+'</p></a>').join('')}
function startLiveCounter(){const el=document.getElementById('liveCount');if(!el)return;let base=1247;setInterval(()=>{base+=Math.floor(Math.random()*9)-4;if(base<1200)base=1200;if(base>1350)base=1350;el.textContent=base.toLocaleString('id-ID')},2500)}
const FEED=['Yadi menyelesaikan Quiz Java 100%','Ani membuka pelajaran HTML','Budi dapat 5 bintang di Game Fix Bug','Citra main Tebak Kode dan menang','Dewi belajar CSS Flexbox','Eko menyelesaikan 10 soal quiz','Fani membuka Playground','Gita menyelesaikan mini game Logic'];
function startLiveFeed(){const el=document.getElementById('liveFeed');if(!el)return;let idx=0;setInterval(()=>{el.style.opacity='0';setTimeout(()=>{el.textContent=FEED[idx%FEED.length];el.style.opacity='1';idx++},400)},3500)}
const NAMES=['Yadi','Ani','Budi','Citra','Dewi','Eko','Fani','Gita','Hadi','Indra'];
const ACTIONS=['menyelesaikan Quiz {topic}','membuka pelajaran {topic}','menang mini game','mendapat 100% di quiz {topic}','menyelesaikan 5 soal berturut-turut','baru bergabung dengan YadCode'];
function getRandomActivity(){const lessons=DB.get('lessons',[]);const name=NAMES[Math.floor(Math.random()*NAMES.length)];const tpl=ACTIONS[Math.floor(Math.random()*ACTIONS.length)];let act=tpl;if(tpl.includes('{topic}')&&lessons.length)act=tpl.replace('{topic}',lessons[Math.floor(Math.random()*lessons.length)].title);return{name,action:act,time:Math.floor(Math.random()*59)+1+' menit lalu',initial:name[0]}}
function renderActivity(){const box=document.getElementById('activityFeed');if(!box)return;const items=[];for(let i=0;i<8;i++)items.push(getRandomActivity());box.innerHTML=items.map(it=>'<div class="activity-item"><div class="activity-avatar">'+it.initial+'</div><div class="activity-text"><b>'+it.name+'</b> '+it.action+'</div><div class="activity-time">'+it.time+'</div></div>').join('');setInterval(()=>{const n=getRandomActivity();const d=document.createElement('div');d.className='activity-item';d.innerHTML='<div class="activity-avatar">'+n.initial+'</div><div class="activity-text"><b>'+n.name+'</b> '+n.action+'</div><div class="activity-time">baru saja</div>';box.insertBefore(d,box.firstChild);while(box.children.length>8)box.removeChild(box.lastChild)},5000)}
function animateStats(){document.querySelectorAll('[data-count]').forEach(el=>{const t=parseInt(el.dataset.count);let c=0;const s=Math.ceil(t/60);const timer=setInterval(()=>{c+=s;if(c>=t){c=t;clearInterval(timer)}el.textContent=c.toLocaleString('id-ID')},25)})}
function initScrollAnim(){const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')})},{threshold:0.1});document.querySelectorAll('.feature-card,.lesson-card,.article-card').forEach(el=>{el.classList.add('fade-in');observer.observe(el)})}
document.addEventListener('DOMContentLoaded',()=>{renderRecommend();startLiveCounter();startLiveFeed();renderActivity();animateStats();initScrollAnim()});
